name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: "rabbitmq:latest"
    strategy:
      matrix:
        go: ["1.15", "1.16"]
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Print Go version
      run: go version
    - name: Debug
      run: which rabbitmq-server
    - name: Start RabbitMQ
      run: "rabbitmq-server &"
    - name: Await node startup
      run: rabbitmqctl await_startup --timeout 60
    - name: Configure RabbitMQ
      run: ./bin/ci/before_build.sh
    - name: Stop RabbitMQ
      run: rabbitmqctl shutdown
    - name: Restart RabbitMQ
      run: "rabbitmq-server &"
    - name: Await node startup
      run: rabbitmqctl await_startup --timeout 60
    - name: Run tests
      run: make
